version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - ./postgres_vol:/var/lib/psql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_database.sql
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: onlygains
    restart: unless-stopped