datasources:
  default:
    dialect: postgres
    db-type: postgres
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:///postgres?currentSchema=app
    username: postgres
    password: postgres

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:db/migration
        - classpath:db/seed