micronaut:
  application:
    name: onlygains
  server:
    host: localhost
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:4200