micronaut:
  application:
    name: myactivepal
  server:
    host: 127.0.0.1
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:4200
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          generator:
            secret: 1d0c3fa23991402e9586555c0f2c6706
            base64: true
            jws-algorithm: HS256
pem:
  path: classpath:config/rsa-2048bit-key-pair.pem

jwt:
  expirationTimeInSeconds: 3600
  issuer: activeServer

encryption:
  initializationVector: RU5DUllQVElPTl9JTklUSUFMSVpBVElPTl9WRUNUT1JFTkNSWVBUSU9OX0lOSVRJQUxJWkFUSU9OX1ZFQ1RPUkVOQ1JZUFRJT05fSU5JVElBTElaQVRJT05fVkVDVE9S
  secret:
    email: "1d0c3fa23991402e9586555c0f2c6706"

datasources:
  default:
    dialect: postgres
    db-type: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myactivepal
    username: postgres
    password: postgres

jpa:
  default:
    entity-scan:
      packages:
        - "com.project"
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:db/migration
        - classpath:db/seed

jackson:
  serializationInclusion: ALWAYS
