micronaut:
  application:
    name: myactivepal
  server:
    host: 127.0.0.1
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:4200
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          generator:
            secret: 1d0c3fa23991402e9586555c0f2c6706

datasources:
  default:
    dialect: postgres
    db-type: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myactivepal
    username: postgres
    password: postgres

jpa:
  default:
    entity-scan:
      packages:
        - "com.project"
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:db/migration
        - classpath:db/seed

jackson:
  serializationInclusion: ALWAYS
